spring:
  application:
    name: rudeFriend-api
  config:
    import: "optional:file:env[.properties]"

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DATABASE_URL:jdbc:mariadb://localhost:3306/rudefriend}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    hikari:
      maximum-pool-size: ${DB_POOL_SIZE:5}

  #  flyway:
  #    enabled: true
  #    baseline-on-migrate: true

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect
    show-sql: true
cloud:
  aws:
    s3:
      bucket: ${AWS_S3_BUCKET}
    region:
      static: ${AWS_REGION}
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_ACCESS_KEY}

logging:
  level:
    root: INFO
    com.lotft.nexus: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(%5p) %clr(%logger{36}){cyan} - %msg%n"

# Swagger
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui/index.html
    try-it-out-enabled: true
  show-actuator: true


jwt:
  secret: ${JWT_SECRET}
  hash-secret: ${JWT_HASH_SECRET}

server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: true
